server:
  port: 9091
  
spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost